<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Products</name>
   <tag></tag>
   <elementGuidId>7db98004-5b5b-436b-8b68-ddaf87dedd0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;aspnetForm&quot;]/div[3]/div[2]/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;aspnetForm&quot;]/div[3]/div[2]/ul/li[1]/a</value>
   </webElementProperties>
</WebElementEntity>
